# Generated by Django 5.2.12 on 2026-04-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitystation",
            name="latitude",
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name="securitystation",
            name="longitude",
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
    ]
