# Generated by Django 5.2.12 on 2026-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0002_alter_securitystation_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitystation",
            name="station_type",
            field=models.CharField(
                choices=[
                    ("police", "Police Station"),
                    ("army", "Army Barracks"),
                    ("fire", "Fire Station"),
                    ("health", "Health Facility"),
                ],
                max_length=20,
            ),
        ),
    ]
